security:
    encoders:
        App\Entity\User:
            algorithm: auto


    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        our_db_provider:
            entity:
                class: App\Entity\User
                property: username
                # if you're using multiple entity managers
                # manager_name: customer

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            provider: our_db_provider
            form_login:
                login_path: login
                check_path: login
                csrf_token_generator: security.csrf.token_manager
                default_target_path: app_dashboard
            switch_user: true

            logout:
                path:   app_logout
                target: login

            # activate different ways to authenticate

            # http_basic: true
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: true
            # https://symfony.com/doc/current/security/form_login_setup.html


    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_ALLOWED_TO_SWITCH]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/security/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/security/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/security/list-users, roles: ROLE_ADMIN }
        - { path: ^/app/dashboard, roles: ROLE_USER }
        - { path: ^/advert/, roles: ROLE_USER }
        - { path: ^/announce/, roles: ROLE_USER }
        - { path: ^/event/, roles: ROLE_USER }
        - { path: ^/municipality/, roles: ROLE_USER }
        - { path: ^/event/, roles: ROLE_USER }
        - { path: ^/ptv/, roles: ROLE_USER }
        - { path: ^/places/to/visit/, roles: ROLE_ADMIN }
        - { path: ^/place/, roles: ROLE_ADMIN }
        - { path: ^/business/, roles: ROLE_USER }
        - { path: ^/business/category/, roles: ROLE_ADMIN }